version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/todos

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/prerequisites.sh
      timeout: 1200
      runas: root

  AfterInstall:
    - location: scripts/install.sh
      timeout: 1200
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
