version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/todos

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 10
      runas: root

  BeforeInstall:
    - location: scripts/prerequisites.sh
      timeout: 1200
      runas: root

  AfterInstall:
    - location: scripts/install.sh
      timeout: 1200
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 10
      runas: root
